name: flutter_app2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 添加依赖
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.3  #屏幕适配
  fluttertoast: ^3.1.3  #吐司
  flutter_swiper: ^1.1.6  #轮播图效果
  dio: ^3.0.2 #网络请求框架
  flutter_easyrefresh: ^2.0.4 #下拉刷新
  webview_flutter: ^0.3.15+1  #WebView
  # https://github.com/flutterchina/cookie_jar
  cookie_jar: ^1.0.0
  dio_cookie_manager: ^1.0.0  #latest version
  shared_preferences: ^0.5.3+4  #shared_preferences
  event_bus: ^1.1.0     #event_bus
  url_launcher: ^3.0.3  #打开浏览器
  image_picker: ^0.6.1+8  #选择图片
  image_cropper: ^1.1.0    #图片剪切
  cached_network_image: ^0.8.0  #网络缓存图片库   # https://github.com/renefloor/flutter_cached_network_image

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    # assets-generator-begin
    # assets/img/*
    - assets/img/ic_empty.png
    - assets/img/ic_error.png
    - assets/img/portrait.png
    - assets/img/collect_1.png
    - assets/img/collect_2.png
    - assets/img/icon_top.png
    - assets/img/ic_back.png
    - assets/img/ic_close.png
    - assets/img/ic_book_normal.png
    - assets/img/ic_book_selected.png
    - assets/img/ic_home_normal.png
    - assets/img/ic_home_selected.png
    - assets/img/ic_project_normal.png
    - assets/img/ic_project_selected.png
    - assets/img/ic_mine_normal.png
    - assets/img/ic_mine_selected.png
    - assets/img/ic_wechat_normal.png
    - assets/img/ic_wechat_selected.png
    - assets/img/ic_close_b.png
    - assets/img/ic_menu_b.png
    - assets/img/ic_refresh.png
    - assets/img/ic_refresh_b.png
    - assets/img/ic_right_b.png
    - assets/img/ic_right_g.png
    - assets/img/ic_share.png
    - assets/img/ic_share_b.png
    - assets/img/ic_swipe_back_b.png
    - assets/img/ic_swipe_back.png
    - assets/img/ic_exit_b.png
    - assets/img/ic_browser_b.png
    - assets/img/ic_exit_b.png
    - assets/img/ic_copy_link_b.png
    - assets/img/ic_collect_b.png
    - assets/img/ic_home_b.png
    - assets/img/ic_home_g.png
    - assets/img/avater.png
    - assets/img/login_bg.png
    - assets/img/img_user_head.png
    - assets/img/logo.png
    - assets/img/logo_android.png
    - assets/img/ic_rank.png
    - assets/img/ic_rank_1.png
    - assets/img/ic_rank_2.png
    - assets/img/ic_rank_3.png
    - assets/img/img_book.png
    - assets/img/img_github.png
    - assets/img/img_heart.png
    - assets/img/img_right.png
    - assets/img/img_setting.png
    - assets/img/img_star.png
    - assets/img/splash_bg.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages






